### ISSUE TITLE
When selecting text in Firefox, fancyInput's text is hidden by the highlight

### ISSUE THREAD

**Issue by notacouch** [yairEO/fancyInput#44]
For my own purposes where the text color (`#color` below) was a shade of blue this is what I used, haven't tested what would fix it for the demo:

(`&` refers to the `<input>`.)

```scss
$color_here: lighten(#color, 15%);
&::-moz-selection {
    background-color: rgba(red($color_here), green($color_here), blue($color_here), .2);
}
```

It seems we have to use the alpha of `rgba` to (lighten the color and) reduce the opacity since `opacity` itself does diddly squat.
